export const manifests: Array<UmbExtensionManifest> = [
  {
    type: 'localization',
    alias: 'ImageHotspot.Localization.En',
    name: 'Image Hotspot English Localization',
    meta: { culture: 'en' },
    js: () => import('./en.js'),
  },
  {
    type: 'localization',
    alias: 'ImageHotspot.Localization.EnUs',
    name: 'Image Hotspot English (US) Localization',
    meta: { culture: 'en-us' },
    js: () => import('./en-us.js'),
  },
  {
    type: 'localization',
    alias: 'ImageHotspot.Localization.Ar',
    name: 'Image Hotspot Arabic Localization',
    meta: { culture: 'ar' },
    js: () => import('./ar.js'),
  },
  {
    type: 'localization',
    alias: 'ImageHotspot.Localization.Bs',
    name: 'Image Hotspot Bosnian Localization',
    meta: { culture: 'bs' },
    js: () => import('./bs.js'),
  },
  {
    type: 'localization',
    alias: 'ImageHotspot.Localization.CsCz',
    name: 'Image Hotspot Czech Localization',
    meta: { culture: 'cs-cz' },
    js: () => import('./cs-cz.js'),
  },
  {
    type: 'localization',
    alias: 'ImageHotspot.Localization.CyGb',
    name: 'Image Hotspot Welsh Localization',
    meta: { culture: 'cy-gb' },
    js: () => import('./cy-gb.js'),
  },
  {
    type: 'localization',
    alias: 'ImageHotspot.Localization.DaDk',
    name: 'Image Hotspot Danish Localization',
    meta: { culture: 'da-dk' },
    js: () => import('./da-dk.js'),
  },
  {
    type: 'localization',
    alias: 'ImageHotspot.Localization.DeCh',
    name: 'Image Hotspot German (Switzerland) Localization',
    meta: { culture: 'de-ch' },
    js: () => import('./de-ch.js'),
  },
  {
    type: 'localization',
    alias: 'ImageHotspot.Localization.DeDe',
    name: 'Image Hotspot German Localization',
    meta: { culture: 'de-de' },
    js: () => import('./de-de.js'),
  },
  {
    type: 'localization',
    alias: 'ImageHotspot.Localization.EsEs',
    name: 'Image Hotspot Spanish Localization',
    meta: { culture: 'es-es' },
    js: () => import('./es-es.js'),
  },
  {
    type: 'localization',
    alias: 'ImageHotspot.Localization.FrCh',
    name: 'Image Hotspot French (Switzerland) Localization',
    meta: { culture: 'fr-ch' },
    js: () => import('./fr-ch.js'),
  },
  {
    type: 'localization',
    alias: 'ImageHotspot.Localization.FrFr',
    name: 'Image Hotspot French Localization',
    meta: { culture: 'fr-fr' },
    js: () => import('./fr-fr.js'),
  },
  {
    type: 'localization',
    alias: 'ImageHotspot.Localization.HeIl',
    name: 'Image Hotspot Hebrew Localization',
    meta: { culture: 'he-il' },
    js: () => import('./he-il.js'),
  },
  {
    type: 'localization',
    alias: 'ImageHotspot.Localization.HrHr',
    name: 'Image Hotspot Croatian Localization',
    meta: { culture: 'hr-hr' },
    js: () => import('./hr-hr.js'),
  },
  {
    type: 'localization',
    alias: 'ImageHotspot.Localization.ItCh',
    name: 'Image Hotspot Italian (Switzerland) Localization',
    meta: { culture: 'it-ch' },
    js: () => import('./it-ch.js'),
  },
  {
    type: 'localization',
    alias: 'ImageHotspot.Localization.ItIt',
    name: 'Image Hotspot Italian Localization',
    meta: { culture: 'it-it' },
    js: () => import('./it-it.js'),
  },
  {
    type: 'localization',
    alias: 'ImageHotspot.Localization.JaJp',
    name: 'Image Hotspot Japanese Localization',
    meta: { culture: 'ja-jp' },
    js: () => import('./ja-jp.js'),
  },
  {
    type: 'localization',
    alias: 'ImageHotspot.Localization.KoKr',
    name: 'Image Hotspot Korean Localization',
    meta: { culture: 'ko-kr' },
    js: () => import('./ko-kr.js'),
  },
  {
    type: 'localization',
    alias: 'ImageHotspot.Localization.NbNo',
    name: 'Image Hotspot Norwegian Localization',
    meta: { culture: 'nb-no' },
    js: () => import('./nb-no.js'),
  },
  {
    type: 'localization',
    alias: 'ImageHotspot.Localization.NlNl',
    name: 'Image Hotspot Dutch Localization',
    meta: { culture: 'nl-nl' },
    js: () => import('./nl-nl.js'),
  },
  {
    type: 'localization',
    alias: 'ImageHotspot.Localization.PlPl',
    name: 'Image Hotspot Polish Localization',
    meta: { culture: 'pl-pl' },
    js: () => import('./pl-pl.js'),
  },
  {
    type: 'localization',
    alias: 'ImageHotspot.Localization.PtBr',
    name: 'Image Hotspot Portuguese (Brazil) Localization',
    meta: { culture: 'pt-br' },
    js: () => import('./pt-br.js'),
  },
  {
    type: 'localization',
    alias: 'ImageHotspot.Localization.RoRo',
    name: 'Image Hotspot Romanian Localization',
    meta: { culture: 'ro-ro' },
    js: () => import('./ro-ro.js'),
  },
  {
    type: 'localization',
    alias: 'ImageHotspot.Localization.RuRu',
    name: 'Image Hotspot Russian Localization',
    meta: { culture: 'ru-ru' },
    js: () => import('./ru-ru.js'),
  },
  {
    type: 'localization',
    alias: 'ImageHotspot.Localization.SvSe',
    name: 'Image Hotspot Swedish Localization',
    meta: { culture: 'sv-se' },
    js: () => import('./sv-se.js'),
  },
  {
    type: 'localization',
    alias: 'ImageHotspot.Localization.TrTr',
    name: 'Image Hotspot Turkish Localization',
    meta: { culture: 'tr-tr' },
    js: () => import('./tr-tr.js'),
  },
  {
    type: 'localization',
    alias: 'ImageHotspot.Localization.UkUa',
    name: 'Image Hotspot Ukrainian Localization',
    meta: { culture: 'uk-ua' },
    js: () => import('./uk-ua.js'),
  },
  {
    type: 'localization',
    alias: 'ImageHotspot.Localization.ZhCn',
    name: 'Image Hotspot Chinese (Simplified) Localization',
    meta: { culture: 'zh-cn' },
    js: () => import('./zh-cn.js'),
  },
  {
    type: 'localization',
    alias: 'ImageHotspot.Localization.ZhTw',
    name: 'Image Hotspot Chinese (Traditional) Localization',
    meta: { culture: 'zh-tw' },
    js: () => import('./zh-tw.js'),
  },
];
